# Generated by Django 4.1.1 on 2022-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact_contact_account_con_created_8bdae6_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='static/images/profile_pic.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
